# Generated by Django 3.2.6 on 2021-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile',
            field=models.ImageField(default='profile/544750.jpg', upload_to='profile'),
        ),
    ]
